/**
 * emit-support.ts — shared helpers for the code-emitter (design.md §4.2).
 *
 * The emitters in `css-codegen.ts` and `dom-codegen.ts` produce TypeScript
 * *source strings*. This module holds the tiny pieces they both need: the
 * {@link GeneratedFile} shape, the `@generated` banner every emitted file must
 * carry (so the Scoreboard's LOC accounting excludes it — Requirement 1.2),
 * and string-literal/identifier helpers that keep emitted code lint-clean.
 *
 * Nothing here is property- or interface-specific; it is pure plumbing.
 */

/**
 * One emitted artifact: a file name (relative to the `generated/` directory)
 * and its full TypeScript source text. The top-level `generate()` collects
 * these; the `bin/generate.ts` writer commits them to disk.
 */
export interface GeneratedFile {
  /** File name relative to the generated directory, e.g. `"css-parsing.ts"`. */
  readonly path: string;
  /** Full source text of the file, including the trailing newline. */
  readonly contents: string;
}

/**
 * Build the `@generated` banner that opens every emitted file. The marker is on
 * line 2 (well within the Scoreboard's 5-line scan window — see
 * `scoreboard/loc.ts`), so emitted files are always classified as generated and
 * excluded from the compat-per-LOC denominator (Requirements 1.2, 1.3).
 */
export function banner(summary: string): string {
  return [
    "/**",
    " * @generated by @browser-engine/generator — DO NOT EDIT BY HAND.",
    " *",
    ` * ${summary}`,
    " *",
    " * Regenerate with `npm run generate --workspace @browser-engine/generator`.",
    " */",
  ].join("\n");
}

/** Quote a string as a TypeScript double-quoted literal (JSON-safe escaping). */
export function quote(value: string): string {
  return JSON.stringify(value);
}

/** Render a list of strings as a TypeScript array literal of quoted strings. */
export function stringArrayLiteral(values: readonly string[]): string {
  return `[${values.map(quote).join(", ")}]`;
}

/**
 * Render a finite number as a TypeScript numeric literal. Throws on a non-finite
 * value so a malformed data row fails loudly during generation rather than
 * emitting `NaN`/`Infinity` into source.
 */
export function numberLiteral(value: number): string {
  if (!Number.isFinite(value)) {
    throw new Error(`cannot emit non-finite number literal: ${String(value)}`);
  }
  return Object.is(value, -0) ? "0" : String(value);
}

/** Upper-case the first character of an identifier (`fontSize` → `FontSize`). */
export function pascalCase(identifier: string): string {
  if (identifier.length === 0) {
    return identifier;
  }
  return identifier[0]!.toUpperCase() + identifier.slice(1);
}

/**
 * Emit an `import` block for a single module: an optional value import line and
 * an optional `import type` line, each only when it has names. Names are sorted
 * for deterministic output. Returns the (possibly empty) lines joined by `\n`.
 */
export function importLines(
  source: string,
  valueNames: readonly string[],
  typeNames: readonly string[],
): string {
  const lines: string[] = [];
  if (valueNames.length > 0) {
    const names = [...valueNames].sort().join(", ");
    lines.push(`import { ${names} } from ${quote(source)};`);
  }
  if (typeNames.length > 0) {
    const names = [...typeNames].sort().join(", ");
    lines.push(`import type { ${names} } from ${quote(source)};`);
  }
  return lines.join("\n");
}
