/**
 * Integration tests for LOC accounting (task 1.7).
 *
 * Built by `tsc` then run with: `node --test packages/scoreboard/dist/*.test.js`.
 *
 * `loc.ts` is the metric *denominator*. These tests pin the integration contract
 * the Scoreboard relies on (Requirements 1.1, 1.2, 1.3):
 *   - blank lines do not count; comment lines do;
 *   - files under a `generated/` directory or carrying a `@generated` marker are
 *     excluded from the hand-written denominator;
 *   - total = handWritten + generated (the honest system-size report).
 */
import test from "node:test";
import assert from "node:assert/strict";
import fc from "fast-check";

import {
  classifyOrigin,
  countSourceLines,
  isGeneratedPath,
  tallyLoc,
  type SourceFileInput,
} from "./loc.js";

void test("countSourceLines counts non-blank physical lines only", () => {
  assert.equal(countSourceLines(""), 0);
  assert.equal(countSourceLines("a\n\nb\n   \nc"), 3);
});

void test("classifyOrigin: generated by directory or by marker, else hand-written", () => {
  assert.equal(classifyOrigin({ path: "src/index.ts", content: "x" }), "hand-written");
  assert.equal(classifyOrigin({ path: "src/generated/x.ts", content: "x" }), "generated");
  assert.equal(
    classifyOrigin({ path: "src/x.ts", content: "// @generated\nx" }),
    "generated",
  );
  // A name that merely contains "generated" is not under a generated/ dir.
  assert.equal(isGeneratedPath("src/generated-helpers.ts"), false);
});

void test("Req 1.2/1.3: tallyLoc splits hand-written vs generated, total includes generated", () => {
  const files: readonly SourceFileInput[] = [
    { path: "pkg/src/a.ts", content: "const a = 1;\nconst b = 2;\n" }, // 2 hand-written
    { path: "pkg/src/generated/b.ts", content: "x\ny\nz\n" }, // 3 generated (dir)
    { path: "pkg/src/c.ts", content: "/* @generated */\nx\n" }, // 2 generated (marker)
  ];
  const tally = tallyLoc(files);
  assert.equal(tally.handWritten, 2);
  assert.equal(tally.generated, 5);
  assert.equal(tally.total, 7);
  assert.equal(tally.total, tally.handWritten + tally.generated);
});

void test("Property: tallyLoc total always equals handWritten + generated", () => {
  // **Validates: Requirements 1.3**
  const arbFile = fc.record({
    path: fc.oneof(
      fc.constant("src/x.ts"),
      fc.constant("src/generated/x.ts"),
    ),
    content: fc.string(),
  });
  fc.assert(
    fc.property(fc.array(arbFile, { maxLength: 30 }), (files) => {
      const tally = tallyLoc(files);
      return tally.total === tally.handWritten + tally.generated;
    }),
  );
});
