/**
 * Tests for the Scoreboard: compat-per-LOC, capability reporting, and graceful
 * publish degradation (task 1.7).
 *
 * Built by `tsc` then run with: `node --test packages/scoreboard/dist/*.test.js`.
 *
 * Covers Requirements 1.1–1.6 and 10.1/10.3:
 *   - 1.1: compat-per-LOC = passing WPT subset tests / hand-written lines.
 *   - 1.2: the denominator EXCLUDES Code_Generator output.
 *   - 1.3: reported total system size INCLUDES generator output.
 *   - 1.4: a capability with no passing WPT test AND no passing reftest is
 *     reported as not implemented.
 *   - 1.5/10.1: a submitted commit runs the configured subset and yields a
 *     pass count.
 *   - 1.6: a publish failure (CI/network) must NOT block the commit.
 *   - 10.3: the current pass count is published.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fc from "fast-check";

import {
  computeCompatPerLoc,
  computeScoreboard,
  publishScoreboard,
  reportCapabilities,
  type ReftestEvidence,
  type Scoreboard,
  type ScoreboardInput,
} from "./scoreboard.js";
import type { SourceFileInput } from "./loc.js";
import type { WptSubset } from "./wpt.js";

// ---------------------------------------------------------------------------
// compat-per-LOC computation (Req 1.1, 1.2, 1.3)
// ---------------------------------------------------------------------------

void test("computeCompatPerLoc divides numerator by hand-written denominator", () => {
  assert.equal(computeCompatPerLoc(10, 100), 0.1);
  assert.equal(computeCompatPerLoc(0, 50), 0);
});

void test("computeCompatPerLoc returns null for a zero (or negative) denominator", () => {
  assert.equal(computeCompatPerLoc(5, 0), null);
  assert.equal(computeCompatPerLoc(5, -3), null);
});

void test("Req 1.1/1.2/1.3: compat-per-LOC uses hand-written lines; total includes generated", () => {
  const sourceFiles: readonly SourceFileInput[] = [
    { path: "packages/css-parser/src/index.ts", content: "const a = 1;\nconst b = 2;\n" }, // 2 hand-written
    {
      // generated by directory → excluded from denominator, included in total
      path: "packages/css-parser/src/generated/props.ts",
      content: "export const X = 1;\nexport const Y = 2;\nexport const Z = 3;\n", // 3 generated
    },
    {
      // generated by marker → excluded from denominator, included in total
      path: "packages/ir/src/dom-surface.ts",
      content: "// @generated by codegen\nexport const w = 1;\n", // 2 generated (marker line counts)
    },
  ];

  const subset: WptSubset = [
    { id: "p1", capability: "color", run: () => true },
    { id: "p2", capability: "color", run: () => {} },
    {
      id: "f1",
      capability: "display",
      run: () => {
        throw new Error("not yet");
      },
    },
  ];

  const board = computeScoreboard({
    wptSubset: subset,
    sourceFiles,
    capabilities: ["color", "display"],
  });

  assert.equal(board.passCount, 2);
  assert.equal(board.loc.handWritten, 2);
  assert.equal(board.loc.generated, 5);
  assert.equal(board.loc.total, 7); // Req 1.3: total includes generated
  // Req 1.1/1.2: numerator / hand-written-only denominator = 2 / 2 = 1.
  assert.equal(board.compatPerLoc, 1);
});

void test("compatPerLoc is null when there is no hand-written code yet", () => {
  const board = computeScoreboard({
    wptSubset: [],
    sourceFiles: [{ path: "src/generated/x.ts", content: "const a = 1;\n" }],
    capabilities: [],
  });
  assert.equal(board.loc.handWritten, 0);
  assert.equal(board.compatPerLoc, null);
});

// ---------------------------------------------------------------------------
// Capability reporting (Req 1.4)
// ---------------------------------------------------------------------------

void test("Req 1.4: a capability with no passing WPT and no passing reftest is not-implemented", () => {
  const reports = reportCapabilities(["color", "grid"], new Set(["color"]), []);
  const byCap = new Map(reports.map((r) => [r.capability, r]));

  assert.equal(byCap.get("color")?.status, "implemented");
  assert.equal(byCap.get("grid")?.status, "not-implemented");
  assert.equal(byCap.get("grid")?.hasPassingWpt, false);
  assert.equal(byCap.get("grid")?.hasPassingReftest, false);
});

void test("Req 1.4: a passing reftest alone marks a capability implemented", () => {
  const reftests: readonly ReftestEvidence[] = [
    { capability: "layout-block", pass: true },
    { capability: "layout-inline", pass: false }, // failing reftest is not evidence
  ];
  const reports = reportCapabilities(
    ["layout-block", "layout-inline"],
    new Set(), // no passing WPT tests
    reftests,
  );
  const byCap = new Map(reports.map((r) => [r.capability, r]));

  assert.equal(byCap.get("layout-block")?.status, "implemented");
  assert.equal(byCap.get("layout-block")?.hasPassingReftest, true);
  assert.equal(byCap.get("layout-inline")?.status, "not-implemented");
});

void test("reportCapabilities de-duplicates capabilities, preserving first-seen order", () => {
  const reports = reportCapabilities(["a", "b", "a", "c"], new Set(["b"]), []);
  assert.deepEqual(
    reports.map((r) => r.capability),
    ["a", "b", "c"],
  );
});

void test("Phase 0 reality: with an empty subset every claimed capability is not-implemented", () => {
  const board = computeScoreboard({
    wptSubset: [],
    sourceFiles: [{ path: "src/index.ts", content: "const a = 1;\n" }],
    capabilities: ["color", "display", "layout-block"],
  });
  assert.ok(board.capabilities.every((c) => c.status === "not-implemented"));
});

// ---------------------------------------------------------------------------
// Graceful publish degradation (Req 1.6) + public publication (Req 10.3)
// ---------------------------------------------------------------------------

function sampleBoard(): Scoreboard {
  const input: ScoreboardInput = {
    wptSubset: [{ id: "p", capability: "color", run: () => true }],
    sourceFiles: [{ path: "src/a.ts", content: "const a = 1;\n" }],
    capabilities: ["color"],
  };
  return computeScoreboard(input);
}

void test("Req 10.3: publishScoreboard publishes the current pass count on success", async () => {
  const board = sampleBoard();
  let publishedCount: number | null = null;
  const result = await publishScoreboard(board, (b) => {
    publishedCount = b.passCount;
  });
  assert.equal(result.published, true);
  assert.equal(result.commitAllowed, true);
  assert.equal(publishedCount, board.passCount);
});

void test("Req 1.6: a synchronous publish failure does NOT block the commit", async () => {
  const board = sampleBoard();
  const result = await publishScoreboard(board, () => {
    throw new Error("network down: 503 from scoreboard host");
  });
  assert.equal(result.published, false);
  assert.equal(result.commitAllowed, true); // commit still proceeds
  assert.equal(result.error, "network down: 503 from scoreboard host");
});

void test("Req 1.6: an async publish rejection does NOT block the commit", async () => {
  const board = sampleBoard();
  const result = await publishScoreboard(board, () =>
    Promise.reject(new Error("CI artifact upload timed out")),
  );
  assert.equal(result.published, false);
  assert.equal(result.commitAllowed, true);
  assert.equal(result.error, "CI artifact upload timed out");
});

void test("Property: publishScoreboard always allows the commit regardless of publisher outcome", async () => {
  // **Validates: Requirements 1.6**
  const board = sampleBoard();
  await fc.assert(
    fc.asyncProperty(
      fc.constantFrom("ok", "throw", "reject"),
      async (mode) => {
        const result = await publishScoreboard(board, () => {
          if (mode === "throw") throw new Error("boom");
          if (mode === "reject") return Promise.reject(new Error("boom"));
          return undefined;
        });
        // The commit is allowed in every case; published is true only when ok.
        return result.commitAllowed === true && result.published === (mode === "ok");
      },
    ),
  );
});
